Fix/svg icons
IDEMSInternational/parenting-app-ui pull request #1143
Opened 2021-12-21 19:01 UTC by chrismclarke

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

The system in place for rendering svgs has a bug where when multiple svgs are on a page some of the styles from one can clash with another (repo issue: `https://github.com/czeckd/angular-svg-icon/issues/73`). We previously highlighted this issue and suggested some ways that content creators could author to avoid, however that is only a temporary fix (and one that's hard to catch or follow-up on)

Instead the PR removes the package entirely to render svgs within native image components. The main benefit of the previous system was the ability to provide custom overrides to svgs with classes, for example to recolour all the lines. However, as we have not implemented such a system yet and similar could be achieved with CSS filters assume fine to replace for now.

## Git Issues

Closes #1127

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2021-12-23 16:11 UTC, EsmeeIDEMS requested changes
Certain images can no longer be found, and the navigation buttons have lost their in-between padding. 

![image](https://user-images.githubusercontent.com/74557272/147265842-4ed4db15-52f5-422e-a18d-220da0d15513.png)

2022-01-04 20:25 UTC, chrismclarke commented
> Certain images can no longer be found, and the navigation buttons have lost their in-between padding.
> 
Fixed, usually all images need an extra piece of code `| plhAsset` that automates loading images from the plh assets folder instead of the local app assets folder. The radio group was missing this for some images, which previously wasn't caught as the custom svg icon component had a fallback to run a second check in case missing. 

I also did a manual check of all other components to see if any other images were missing the plhAsset code and all others looked fine, although there is a bit of inconsistency because some components do use hardcoded images from local assets (e.g. timer icons) and others hardcoded plh assets (e.g. star icons), so that might be something to tidy up from the dev side in the future (i.e. have some hardcoded default icons that can be overridden)

2022-01-05 15:52 UTC, volloholic approved these changes

2022-01-05 16:23 UTC, chrismclarke commented
Reviewed on call, changes implemented, merging

2022-01-05 16:23 UTC, merged