Feat/accordion component
IDEMSInternational/parenting-app-ui pull request #1188
Opened 2022-01-21 04:17 UTC by chrismclarke

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

- Add accordion component
- Update debug template to include standard and fully customised versions

## Author Notes
A few minor alterations were made to the proposed syntax, see comments in purple
https://docs.google.com/spreadsheets/d/1gfnWmr59DF0ZsuSuBh0K1o9fMqEg-z6Qa7eJNsiB-rQ/edit#gid=63099847

I haven't included any documentation for the new component, should ideally be done once finalised

## Dev Notes
The accordion component use new `accordion` block and does not attempt to reuse the existing workshop_accordion (judged not worth the effort). However, both the workshop and new accordion use the same component type to define nested children as `accordion_section`. The workshop component creates a second component to handle this, but the new accordion component just renders the nested content directly instead (assumes all direct children of accordion elements will be accordion sections)

This means that for now we are fine with the naming conflict, however if we ever decide to remove/refactor the workshop accordion we will need to remember to leave a blank placeholder to still allow the accordion_section type column (simply as a means of grouping child content in the accordion).

## Git Issues

Closes #1115

## Screenshots/Videos

https://user-images.githubusercontent.com/10515065/150464766-4531c4ea-b825-4dd8-b0e0-924c17731bf8.mp4

2022-01-21 08:47 UTC, EsmeeIDEMS requested changes
This looks great, thanks. Can you rename `openMultiple` to `open_multiple` so that it's in line with the naming conventions?

2022-01-21 19:18 UTC, chrismclarke commented
> This looks great, thanks. Can you rename openMultiple to open_multiple so that it's in line with the naming conventions?

Sure thing, just done. Have also added shadow effect as in designs.

2022-01-24 08:37 UTC, EsmeeIDEMS approved these changes
Functional test passed.

2022-01-24 13:59 UTC, volloholic approved these changes

2022-01-24 13:59 UTC, merged