Feat/app minimize
IDEMSInternational/parenting-app-ui pull request #1191
Opened 2022-01-22 03:02 UTC by chrismclarke

PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

Capacitor (finally) released functionality to allow the app to be minimised (briefly could only be fully closed). As a result when pressing back button on the home screen running on an android device nothing happens.

This PR changes behaviour so that if back button is pressed on the home screen the app minimises (as is common for most other apps).

## Review Notes
As this can only be tested on a physical device recommend creating apk for branch (`feat/app-minimize`) using github actions and then either running on a local device/emulator or upload apk to test online via https://appetize.io/

## Dev Notes
Various core plugins have been updated to include the new feature. These are all minor version updates and so not expected to have any breaking changes.

## Git Issues

Closes #

## Screenshots/Videos

2022-01-22 06:19 UTC, chrismclarke commented on packages/data-models/constants.ts
>  };
authoring option that handles which route to consider home page and minimise on back button push

2022-01-22 06:21 UTC, chrismclarke commented on package.json
> +    "@capacitor/android": "^3.4.0",
All package updates are minor version bumps only, so not expected to introduce any breaking changes

2022-01-22 06:22 UTC, chrismclarke commented on src/app/shared/components/plh-main-header.ts
> +      });
listener to add handling to hardware back button press

2022-01-22 06:23 UTC, chrismclarke commented on android/app/capacitor.build.gradle
> +    implementation project(':capacitor-clipboard')
when we previously added clipboard copy feature some of the linked dependencies were not tracked in main repo. This isn't really an issue as they are re-populated automatically during build on the server, but added now for tidyness

2022-01-24 09:06 UTC, EsmeeIDEMS commented
I get this message about half of the time when I refresh the screen in Appetize. Is that expected? Should I create my own account?

![image](https://user-images.githubusercontent.com/74557272/150752663-08b5cc58-42ef-4e03-ad21-5e57863612ad.png)

2022-01-24 09:29 UTC, EsmeeIDEMS requested changes
When testing on Appetize, it seems that only the first action on the Language page works: when "next" is clicked immediately, the page closes correctly, but when first a language is selected, neither the radio group nor the "next" button responds any longer. 

(N.B. on the Terms and Conditions page multiple actions do seem to work, after launching pop-ups the "next" button still works.)

App gets stuck when interacting with language radio group:

https://user-images.githubusercontent.com/74557272/150756194-d4111ebc-f380-48ab-8903-b5bbadd5609c.mp4

App doesn't get stuck when not interacting with language radio group:

https://user-images.githubusercontent.com/74557272/150756626-45228ea6-3c73-456f-9920-6459a86f8139.mp4

2022-01-24 18:11 UTC, chrismclarke commented
> When testing on Appetize, it seems that only the first action on the Language page works: when "next" is clicked immediately, the page closes correctly, but when first a language is selected, neither the radio group nor the "next" button responds any longer.
> 

I get the same issue locally so it's not specific to appetize. Will convert to a separate issue and suggest merging here unless there are any other issues noted.

2022-01-25 09:30 UTC, volloholic approved these changes

2022-01-26 15:44 UTC, EsmeeIDEMS approved these changes

2022-01-26 15:44 UTC, merged