feat: add force_restart emit action
IDEMSInternational/parenting-app-ui pull request #1220
Opened 2022-02-03 22:33 UTC by chrismclarke

PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

We have 2 (confusingly named) actions `force_reload` and `force_reprocess` that both trigger re-evaluation of templates (with reload re-evaluating fully and reprocess just checking for variable changes). Neither, however re-evaluate content that is sat outside the current template page, such as the app menu.

As an interim solution I've added a `force_restart` action that does a more heavy-handed full page reload and redirect to the home page (like when running app reset).

I've also updated the authoring to perform a restart when changing between dev and user mode from the settings screen.

## Review Notes
There's no easy way to review the changes, because when running locally the app is forced into dev mode regardless. So we will need to sync the latest content with the authoring changes and deploy to the web version to test. 

But by temporarily blocking the local app overrides all behaves as expected in video below

## Git Issues

Closes #

## Screenshots/Videos

https://user-images.githubusercontent.com/10515065/152440306-b304171b-8794-4b4c-b5aa-e1ac1b58ee22.mp4

2022-02-04 18:48 UTC, EsmeeIDEMS requested changes
This relates to issue #1013, do you want to close it or should we leave it open since this is only an interim solution? 

I wanted to use this also on the [language_select](https://docs.google.com/spreadsheets/d/1iSG1kzK4OTHcoiwWoZ25LZxrJqERg2_iP9369HTi_bQ/edit#gid=823624970) template (so that the side menu updates to the correct language when the language is changed). This could be either on the radio group directly
`changed | emit: force_restart`
or on the nav_buttons template
`completed | emit:force_restart`
However, neither seems to work (the console says `force_reload` in one case and `force_restart` in the other, but I never get redirected to the home screen)
<img width="532" alt="image" src="https://user-images.githubusercontent.com/74557272/152585576-e2c90e82-34da-4c41-9951-c97c22ff553c.png">

2022-02-04 19:08 UTC, chrismclarke commented
I think best to leave open, the language select is a little bit tricker because the way things are currently authored changing the language during the startup screen would reload the app but skip the rest of the slides. Really I just need to add a better means to update the menu, so good to keep open

2022-02-06 05:32 UTC, volloholic approved these changes

2022-02-07 19:18 UTC, EsmeeIDEMS approved these changes

2022-02-07 19:19 UTC, merged