[DRAFT] - Feat/data pipe parser integration
IDEMSInternational/parenting-app-ui pull request #1494
Opened 2022-08-28 19:38 UTC by chrismclarke

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

Integrate 

## TODO (future checklist)
- Add methods to allow runtime re-evaluation of data pipes

## Review Notes
The data_pipe feature contains a significant number of moving parts, 

- Add more example flows to test expected functionality, including complex examples where outputs from one pipe depend on another
- Test example flows in various scenarios, e.g. changes to pipe, changes to input_source etc. to check for any potential caching issues

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2022-09-06 15:28 UTC, volloholic approved these changes

2022-09-07 18:02 UTC, EsmeeIDEMS requested changes
I'm trying to author a data-pipe sheet that uses `map` followed by `concat`, however, this doesn't work (nothing appears in the generated subfolder). My current hypotheses (might be wrong) are that 
1. A `concat` row expects a blank `input_source`, but when it's not the first row on a `data_pipe` sheet blank means "`input_source` equals `output_target` from previous row" so things might get confused
2. It looks like `concat` doesn't work with generated lists

See the sheet [workshop_tasks_pipe ](https://docs.google.com/spreadsheets/d/1kdhunjNQ6xM9cnK7M0J4UneQ9zvasagWGAT9LEH2Xr0/edit#gid=640656823)

2022-09-08 13:46 UTC, EsmeeIDEMS approved these changes
I realised the issue I came across previously was actually explained in the documentation...

2022-09-08 13:47 UTC, merged

2022-09-14 09:43 UTC, jfmcquade commented on packages/scripts/src/commands/app-data/convert/processors/xlsxWorkbook.spec.ts
> +  }
Add underscore to flow_name