chore: code tidying
IDEMSInternational/parenting-app-ui pull request #1775
Opened 2023-02-04 03:05 UTC by chrismclarke

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

_What this PR does_

## Review Notes
As changes are only to parsers the main check is that content synced is processed the same as previously.

The parser includes a version bump which should invalidate the cache and force all sheets to be reprocessed (around 265 sheets or so on plh global config). If this is not the case (e.g. retesting) all caches can be cleared via `yarn workflow clear_workflow_cache`

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2023-02-06 16:36 UTC, jfmcquade requested changes
Looks good. 

The theme functionality (correctly handling assets when switching themes) seems to be preserved, both from inspecting the code and some functional testing. 

I flagged in the inline comments that an error is thrown when a deployment does not specify a value for `filter_language_codes`. I think this is actually indicative of a broader issue: when setting a deployment to active and compiling the `activeDeployment.json` file, default values are not set for `local_drive`, `app_data`, `translations` and `workflows`.
This means that values that are not specified in a deployment's config cannot be drawn upon correctly as they may be undefined. See screenshots of errors thrown when running a sync with `wash` as the active deployment:
<img width="800" alt="Screenshot 2023-02-06 at 16 15 33" src="https://user-images.githubusercontent.com/64838927/217026593-db04c8ab-2f57-4688-90dc-0c6538fdf367.png">
<img width="800" alt="Screenshot 2023-02-06 at 16 14 57" src="https://user-images.githubusercontent.com/64838927/217026601-13b0eb87-c24d-410c-a405-169b8fa58eff.png">

Should those values be populated by the default deployment config values from `DEPLOYMENT_CONFIG_EXAMPLE_DEFAULTS` in `packages/data-models/deployment.model.ts`? Or should consumers of the `activeDelpyment` config merge in the defaults after getting `ActiveDeployment.get()`?

2023-02-06 18:18 UTC, chrismclarke commented
> when setting a deployment to active and compiling the activeDeployment.json file, default values are not set for local_drive, app_data, translations and workflows.

Nice catch @jfmcquade - yes each deployment should inherit the defaults from [DEPLOYMENT_CONFIG_EXAMPLE_DEFAULTS](https://github.com/IDEMSInternational/parenting-app-ui/blob/refactor/app-sync-scripts/packages/data-models/deployment.model.ts#L74-L75) but that only happens when config defined when defined in the newer syntax
```
import { generateDeploymentConfig } from "scripts";
const config = generateDeploymentConfig("plh");
```

I can see WASH still has the older syntax
```
import { getDefaultAppConfig } from "data-models/appConfig";
const app_config = getDefaultAppConfig();
```
So will update it now

2023-02-06 18:33 UTC, chrismclarke commented on src/app/shared/components/template/services/template-asset.service.ts
> +    const themeFolderName = this.themeService.getCurrentTheme();
agreed, updated in fa03eb33e64332b195aa52f5c32648a81aa63499

2023-02-07 19:13 UTC, chrismclarke commented
@jfmcquade 
I've just merged the pr to fix the wash deployment config. I realised the issue you flag still persists because the default value for the language codes was `null` and not `[]`, so I've added the extra conditional checks as well so hopefully should be all resolved now. Have requested re-review

2023-02-08 14:32 UTC, jfmcquade approved these changes
Looks good, the issue I flagged is fixed. The CLI experience of switching deployments and syncing the respective content is smooth

2023-02-08 14:35 UTC, esmeetewinkel requested changes
I found a bug, on the PLH TZ deployment the image assets don't seem to update correctly with the theme. 

To recreate: 
1. `yarn workflow deployment set plh_tz`
2. `yarn workflow clear_workflow_cache`
3. `yarn workflow sync`
4. `yarn start`
5. Navigate to http://localhost:4200/template/language_select and set language to English
6. Navigate to http://localhost:4200/template/skin_select, type the code `app_dev` and select `module`. This should set the skin to be the modular skin and the theme to be the professional theme. 
7. The homescreen now shows the professional theme but with images from the default theme.  
<img width="948" alt="image" src="https://user-images.githubusercontent.com/74557272/217559587-80e40d04-208e-40a2-bc3f-1a8a3173e086.png">

N.B. the audio assets DO seem to change correctly when changing language between English and Swahili

2023-02-08 20:04 UTC, chrismclarke commented
Thanks for catching that @esmeetewinkel , you are right that none of the theme assets were being copied over.

I've added a fix for the issue and additional test to track the behaviour in the future so hopefully should be working now as expected

![image](https://user-images.githubusercontent.com/10515065/217638993-a40c8316-4aac-46d7-88af-14dbf375fec0.png)

2023-02-09 20:55 UTC, merged