feat: wip add odk form component
IDEMSInternational/parenting-app-ui pull request #1926
Opened 2023-05-23 20:47 UTC by chrismclarke

PR Checklist

- [ ] PR title descriptive (can be used in release notes)

## Description

Add `odk_form` template component to render odk forms.

**TODO**
- [x] Component renderer
- [ ] Example templates
- [ ] Documentation

**Known Issues**
- Component adds requirement for a lot of extra 3rd party dependencies (e.g. jquery, bootstrap-datepicker). These could be reduced by removing/replacing specific widgets (e.g. datepicker), however this would require additional work and careful documentation in case full compatibility is not kept with ODK.

- Style files in particular are very large, requiring change to build budgets

- Image attachments not yet rendering

- Multi-page forms are all shown on a single screen 

## Dev Notes
Originally it had been planned to build this as a standalone webcomponent and import, however as the standalone version is not yet ready for publishing the codebase has been copied and adapted to work directly in angular. The benefit of this is further adjustments that could be made to customise the component and reduce bundle sizes

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2023-06-09 09:40 UTC, volloholic commented
@chrismclarke I have been discussing with Esmee and am not clear how https://xlsform.org/en/#multiple-choice-from-file would work? Does the population happen as part of the enketo Json creation process or is it still a live link then?

2023-06-13 15:05 UTC, esmeetewinkel requested changes
Workflow works fine for me, I've been able to set up docker / convert my own ODK `.xlsx` form / show it in the app (deployment [plh-facilitator](https://github.com/IDEMSInternational/plh-facilitator-app-content), template [odk_form_en](https://docs.google.com/spreadsheets/d/1HfQVzBWW4-LoclVGIhumk8aMjNOHJ-fueHetcxd2QXI/edit#gid=1321716080))

<img width="235" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/465b5556-6f1a-4d8c-ba76-fbd6204964dd">

#### Comments: 
- The display looks quite funky. It seems that line breaks are not working, nor does conditionality. Also the text is black rather than inheriting the dark blue colour from our app theming. 
- How would I go about saving the outcome of a form to something we can access on the server, e.g. a contact field? 
- We would eventually need this to work with translation (which you observed already). When loading a multi-language ODK form into this at the moment, all languages are displayed (deployment [plh-facilitator](https://github.com/IDEMSInternational/plh-facilitator-app-content), template [odk_form](https://docs.google.com/spreadsheets/d/1HfQVzBWW4-LoclVGIhumk8aMjNOHJ-fueHetcxd2QXI/edit#gid=378849870))
<img width="234" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/bca31ce2-ee4f-41b7-a9c8-1b1bd3adeda5">

2023-06-19 16:26 UTC, chrismclarke commented
> @chrismclarke I have been discussing with Esmee and am not clear how https://xlsform.org/en/#multiple-choice-from-file would work? Does the population happen as part of the enketo Json creation process or is it still a live link then?

@volloholic 
Good question - I think we will need a minimal demo repo to see what the current behaviour is and then a discussion for what is required. As far as I can remember the csv is processed during form conversion, so only really supports a static list. I remember at Stats4SD we had to come up with a bunch of custom methods to recreate forms whenever supporting csvs changed to be able to populate with 'live' data.

Enketo does have support for custom widgets however, so if longer term we do need some extra functionality we could look into it

2023-06-19 16:38 UTC, chrismclarke commented
@esmeetewinkel 
> The display looks quite funky. It seems that line breaks are not working, nor does conditionality. Select questions appear in side a (double) box, but no other question type does. Also the text is black rather than inheriting the dark blue colour from our app theming.

Just pushed a PR to fix the issue where enketo styling was not correctly being applied (new screenshot below). These enketo styles are quite complex and opinionated, so would recommend it being a follow-up task if we wanted to create our own custom theme to better inherit from the app styles.
![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/10515065/68bddc2b-8d14-4d27-9ee0-91a76fae81fa)

> How would I go about saving the outcome of a form to something we can access on the server, e.g. a contact field?

The odk_form component is structures the same as any other input type component, so you can use the `changed` action trigger to save the value to a contact field. I can see from your demo you are already reading this value when populating the text at the bottom of the screen
![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/10515065/e8dd3492-ad5f-4ce5-a215-e11ffe569498)

The main issue is that enketo keeps all data written in xml format which isn't as easily interpreted as json would be. It's possible to convert xml to json, however I haven't done that up till now as it's quite hard to later reverse the process if we wanted to read back in the json record. E.g. the xml logged and stored in the value could be converted using the online converter
https://codebeautify.org/xmltojson
![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/10515065/43f20ffd-9623-434d-a1dd-60cb5795cab1)

A short term workaround could be to store the result as both xml and json when we save (would require adding an extra 3rd party lib to convert like https://github.com/NaturalIntelligence/fast-xml-parser)

> We would eventually need this to work with translation (which you observed already). When loading a multi-language ODK form into this at the moment, all languages are displayed (deployment [plh-facilitator](https://github.com/IDEMSInternational/plh-facilitator-app-content), template [odk_form](https://docs.google.com/spreadsheets/d/1HfQVzBWW4-LoclVGIhumk8aMjNOHJ-fueHetcxd2QXI/edit#gid=378849870))

This should now be fixed with the style fixes
![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/10515065/86e8aaf8-7f75-4fa6-960d-182aac3b0b35)

2023-06-20 10:50 UTC, esmeetewinkel approved these changes
Thanks @chrismclarke. Display looking much better, conditionality and translations work. I'm happy to leave the styling as-is for now. Approving this since I'm happy for this PR to be merged and to continue working on the issues flagged below in a follow-up PR. I'll leave it up to you to decide.

I'm able to save the XML output of the form to a field using the `changed` trigger. This saves the field every time any input of the form is changed. However, when using `start` and `end` in the ODK form the timestamps are both the same and do not change as I continue filling the form. (e.g. in Facilitator app deployment [ePLH_Pilot_Facilitator_Weekly_Survey_Combined.xlsx](https://github.com/IDEMSInternational/parenting-app-ui/files/11799058/ePLH_Pilot_Facilitator_Weekly_Survey_Combined.xlsx) = [converted json](https://drive.google.com/file/d/18lQPcLiC40Il6vXAysPJCMoOW10-QiN-/view?usp=drive_link))

Are we thinking of using the "Save Draft" and "Submit" buttons? If yes, how would I author their actions? If no, should we hide them (and use buttons in our regular syntax to achieve the same)?

<img width="248" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/587cba10-9de9-47cc-a4be-4bebfada1159">

2023-06-22 10:51 UTC, chrismclarke commented
I've added #1926 to track issues flagged here.
So I think once @jfmcquade has reviewed should be good to go

2023-06-22 15:05 UTC, jfmcquade approved these changes
Looking good. Some minor comments/questions inline.

A few more comments:
- On narrow screens, the "Save Draft"/"Submit" buttons don't wrap or shrink so stick out of their container. I know there's a TODO to handle them better, so if they end up being kept then this styling should be fixed
<img width="400" alt="Screenshot 2023-06-22 at 15 38 24" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/20ae5dc4-de48-41a8-9d34-27418db7718b">

- Bundle size. You've included notes on what to remove (in `src/app/shared/components/template/components/odk-form/odk-form.component.ts`) if we want to "opt-out" of the ODK form feature, e.g. to reduce bundle size. I'm highlighting here mainly to make @esmeetewinkel aware that there is a brute force way to reduce the bundle size (by manually removing modules of code) if necessary for the next release of plh_tz, for example.

- It could be good to update the PR description to remove the TODO checklist, and link to #1964 instead

2023-06-23 12:04 UTC, esmeetewinkel commented
Merging this as I need it for a deployment. Hopefully outstanding minor issues can be addressed in a follow-up PR.

2023-06-23 12:04 UTC, merged

2023-06-25 07:52 UTC, chrismclarke commented on .idems_app/deployments/plh_facilitator
I think the files possibly were once there but then removed... I'll leave tidying it for a future PR

2023-06-25 08:00 UTC, chrismclarke commented on .idems_app/deployments/plh_facilitator
resolved in #1926

2023-06-25 08:00 UTC, chrismclarke commented on src/app/shared/components/template/components/odk-form/odk-form.component.scss
> +// apply margin to fit section dropdown arrows (breakpoints from _responsiveness.scss)
resolved in #1926

2023-06-25 08:01 UTC, chrismclarke commented on src/app/shared/components/template/components/odk-form/odk-form.component.scss
> +  // give form a chance to load/render before showing unavailable message
I was so sure that I must have copied this directly from the enketo-express implementation somewhere but can't seem to find it anymore so maybe that was all just a dream... In any case I think should serve our purpose fine for now

2023-06-25 08:03 UTC, chrismclarke commented on src/app/shared/components/template/components/odk-form/odk-form.component.ts
> +    // await this.setValue(this.xmlFormValue);
Yeah it's a bit confusing/messy to try and stay comparable with enketo, however I think I realised that the previous `handleEventDataUpdate` also triggers at the same time which currently handles our saveValue and triggerActions code, so possibly redundant. But may be reviewed when we also want to review the save draft/submit functionality

2023-06-25 08:07 UTC, chrismclarke commented on src/app/shared/components/template/components/odk-form/odk-form.component.ts
> +   * https://enketo.github.io/enketo-core/tutorial-00-getting-started.html
Looks like it's moved, actually follows the code snippets from https://github.com/enketo/enketo-core#usage-as-a-library
resolved in #1926

2023-06-25 08:14 UTC, chrismclarke commented on packages/data-models/workflows/sync.workflows.ts
> +          if (options.skipDownload) {
If I remember correclty all options defined at the start of the workflow are parsed using the same parser that [Commander.JS](https://www.npmjs.com/package/commander) uses, which by default turns options defined in `kebab-case` to `camelCase`. I assume this is for ease of authoring/convention, and is also the system we use for all the main workflow execution so makes sense to author in a similar way

2023-06-25 08:17 UTC, chrismclarke commented on src/app/shared/components/template/components/odk-form/odk-form.component.ts
> +  private parameter_list: IODKFormComponentParameters;
Resolved in #1926