Fix: checkbox width shrinking issue
IDEMSInternational/parenting-app-ui pull request #1983
Opened 2023-07-17 15:49 UTC by kwAsant

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Fixes an issue where the checkbox component would shrink to a rectangular shape whenever the width of the screen gets smaller.

## Git Issues

Closes #1739 

## Screenshots/Videos

[comp_simple_checkbox](https://docs.google.com/spreadsheets/d/19t6lEBkVF0LV2dMD1yL6nbuUIFiiYNa0xLA1QQAyyxU/edit#gid=569531329) showing the checkboxes remaining square-shaped.

<img width="450" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/88288104/2e0be023-4808-4f15-8583-87fa6c2d083d">

2023-07-18 10:44 UTC, jfmcquade requested changes
Looks good, well done!

As an extra point that wasn't included in the issue: I think that the CSS variable `--checkbox-border-size` is mis-named: it should just be `--checkbox-size` I think. I think it would make sense to change that as part of this PR as you're looking at that code.

Could you change the name of that variable everywhere it appears in the code? I.e. search in VSCode for "--checkbox-border-size" and change all instances, I think there are 3 instances across 2 files.

2023-07-18 14:53 UTC, kwAsant commented
Changes have been made, as per requested.

2023-07-19 10:09 UTC, jfmcquade approved these changes
LGTM, thanks.

I'll leave it to Esmee to do some functional testing

2023-07-19 12:11 UTC, esmeetewinkel approved these changes
Thanks both, functional test passed!

2023-07-19 12:11 UTC, merged