Fix/dashed box component
IDEMSInternational/parenting-app-ui pull request #1985
Opened 2023-07-18 09:54 UTC by kwAsant

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Addresses errors where line breaks were not considered within the dashed-box component.

## Git Issues

Closes #1152 

## Screenshots/Videos

[debug_dashed_box_paragraphs](https://docs.google.com/spreadsheets/d/1rtqqvxb50wGa00AJcF3GcTeUdxLky2pcK84mA8G0Few/edit#gid=383748944)

<img width="417" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/88288104/60150db1-6da1-44b6-9984-3b67d9bc9d71">

2023-07-19 12:17 UTC, esmeetewinkel approved these changes
Functional test passed.

2023-07-19 13:01 UTC, jfmcquade requested changes
Good work, this solves the issue. I've added a comment inline where I think you can remove some code.

2023-07-19 13:01 UTC, jfmcquade commented on src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
> +        margin-bottom: 0.75em 0 ;
I don't think this CSS rule is doing anything so it's not needed. As far as I can tell, the text that gets rendered is passed in as `innerHTML`, so there are no `<p>` elements inside `.text`. I would recommend deleting this rule unless there's a reason for it

2023-07-20 09:48 UTC, jfmcquade approved these changes
LGTM

2023-07-20 09:56 UTC, merged