fix: data items are sorted according to original order by default
IDEMSInternational/parenting-app-ui pull request #2312
Opened 2024-05-02 15:38 UTC by jfmcquade

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

As documented in #2311, item rows within a `data-items` loop are sorted according to their ID value by default. Whilst we do have a `sort` operation that can be applied to the items via the parameter list of the data-items component, which can be used to sort the list based on some property of the items, there is currently no way to reference the original order of the items in the data list.

This PR makes it the default that data-items render in the order that matches the original data list.

## Git Issues

Closes #2311

## Screenshots/Videos

Template [debug_data_items_order](https://docs.google.com/spreadsheets/d/1HvJOcbYGtrkPxwkPp8lvNW63ngsvworzz_jEUo5Swe0/edit#gid=1681985300), reading from [debug_data_list_order](https://docs.google.com/spreadsheets/d/1HvJOcbYGtrkPxwkPp8lvNW63ngsvworzz_jEUo5Swe0/edit#gid=275599747) showing items displayed in the expected order.

<img width="120" alt="Screenshot 2024-05-02 at 16 38 00" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/7b371c9c-3a4c-4acd-81b1-d1fc8ba27aaa">

<img width="300" alt="Screenshot 2024-05-02 at 16 38 16" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/c385ac14-5bdf-41d4-8875-d73caa5e2a02">

Passing tests:
<img width="400" alt="Screenshot 2024-05-02 at 16 30 31" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/4ff09ea5-da4e-4e31-ba6b-cac532afddb0">

2024-05-02 15:44 UTC, jfmcquade commented on src/app/shared/services/dynamic-data/dynamic-data.service.ts
> +        index_original: initialData.indexOf(el),
Originally I was going to name this field "_index", however RxJs throws an error when trying to use a field name that starts with an underscore: `RxError: fieldnames do not match the regex:"^[a-zA-Z](?:[[a-zA-Z0-9_]*]?[a-zA-Z0-9])?$"`. Using "_index" might also get it confused with the `_index` of an item in `itemContext`, which is the index within the array of items to render, after any operations have been performed on the original data.

So it's an open question as to what this field could be named. It should be something that we're not going to overwrite as a property of the item. With #2310 in mind, we could prefix protected properties with a custom prefix: e.g., in this case we call the field something like `PROTECTED_index`, and as a solution to #2310, we append any field name that starts with `_` with the prefix "protected", e.g. `PROTECTED_translations`. Thoughts?

2024-05-02 20:41 UTC, chrismclarke requested changes
Ah of course, given the `id` column is a primary key we lose all default sorting for any data not in alphabetical order. I like the solution to populate and track the additional metadata fields, a couple minor suggestions:

1. I think it would be good to include the metadata field as part of the schema for both the `persistedMemory` and `reactiveMemory` adapters. That way we can also mark as an [index](https://rxdb.info/rx-schema.html#indexes) column type to make it more efficient to retrieve ordered data. 

2. We may also want to consider marking the column as a [final](https://rxdb.info/rx-schema.html#final) column type to prevent user writes to the column, although should first test if we're still able to populate and repopulate data on initial load with updated index (possibly just consider later).

3. For the naming convention appreciate we can't start with underscore. Given we already use `row_id` as a column for persisted data I'd probably recommend using `row_index` instead of `index_original`. This can be defined in the schemas as an integer type. I think probably no need to specifically mark `PROTECTED` columns as I think even if users included their own `row_index` column it will just get overwritten by the generated one, and if wanting to provide a better way for users to sort data then this can be handled elsewhere.

4. Instead of relying on sorting data within component I think it might be better to make the default behaviour to return rows in the `row_id` order unless otherwise specified. So likely updating the adapter `query$` method to automatically specify the [query index](https://rxdb.info/nosql-performance-tips.html#set-a-specific-index) as `row_id` 

Let me know if this makes sense and if you need me to do anything else for support on this PR

2024-05-13 14:01 UTC, chrismclarke commented
> This does seem to work and still allow us to update the index if the data changes. See demo below (with some waiting time cut out): I make a user write over some data, then change the order of that data (changing the index for each item) and make additional writes. You can see that the `row_index` property remains the same until a write is made specifically to that item, at which point it successfully updates to reflect the new order. Does this cover the case you were thinking of? 

Great, yeah that works really nicely, because the `row_id` is a top-level property and only the inner `data` property is persisted/merged then it means we will always preserve the `row_index` from parsing the sheet. I also noticed in the rxdb code that the final field is only enforced in dev mode (guessing performance reasons, seems reasonable to me given we're more likely to explore implementation during dev anyways), so production is a little more forgiving anyways.

> I'm not quite sure how to put this into a spec test, but I've added one that confirms the `row_index` property cannot be overridden via the `DynamicDataService.update()` method. Are there any more cases related to setting the column to `final` that might not be covered?

I think that's sufficient, our spec tests cover the metadata population and inner data merge so would be a bit artificial adding tests right now for things that don't exist/won't happen. I manually tested migration switching between branches, had looked at adding a spec test but decided would be more effort than its worth as we'd need to totally decouple the schema/migration files from the service code (to be able to replace it more easily), which doesn't seem worthwhile when we're unlikely to change these much again in the future.

2024-05-13 14:06 UTC, chrismclarke commented on src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
> +    const newDoc = { ...oldDoc, row_index: 0 };
+1 - I took a quick look to see if there was any way to get the actual index but not passed to rxdb migration executor so I think your workaround to just make identical and use secondary sort index based on id is the best option

2024-05-13 14:09 UTC, chrismclarke approved these changes
Thanks @jfmcquade - a really like this implementation, nice to be able to handle all the logic just from within the service code and also appreciate the tests and migration implementations.

I've added one minor code tidying commit with 307225 (think the auto wrap left an empty type interface for whatever reason), but otherwise I'd say should be good to go

2024-05-15 12:39 UTC, merged