Issue 927 Tile Height
IDEMSInternational/parenting-app-ui pull request #996
Opened 2021-08-31 09:31 UTC by zulkifelff

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

Due to the difference in textual data, the height of tiles varies. Template _debug_tile_text_ illustrates that issue. Now this PR direct toward this issue and fixed tile heights.

## Git Issues

[Issue 927](https://github.com/IDEMSInternational/parenting-app-ui/issues/927)

## Screenshots/Videos
![Tiles_2](https://user-images.githubusercontent.com/45070594/131478816-043dc910-dd9f-44fe-90e1-d47953e1cc18.png)
![Tiles_1](https://user-images.githubusercontent.com/45070594/131478831-053e61f6-55ba-423f-b5e4-8eb185c7e98a.png)

2021-08-31 10:04 UTC, chrismclarke approved these changes

2021-08-31 10:29 UTC, chrismclarke requested changes
As discussed on the call, we want to use grid layout so keep tile size consistent.

I also suggest that we do not need to increase the `min-height`, `10rem` looks sufficient to display content that is short

2021-09-07 09:56 UTC, zulkifelff commented
![Screenshot (162)](https://user-images.githubusercontent.com/45070594/132325304-9f936dab-c3c3-4871-b94c-ebb60fcfed09.png)
Corrected the issue.

2021-09-07 21:23 UTC, chrismclarke approved these changes
Looks better to me now, many thanks. Merging

2021-09-07 21:23 UTC, merged